# Cobertura e dominância de samambaias epífitas em *Tipuana tipu*

> Grupo 1: Francelino, A.C., Ribeiro, C.F.F., Santos, G.P., Batista, L.R.C., Bergmann, M.A. e Cirino, D.W.

> Orientador: Douglas William Cirino


Plantas pteridófitas utilizam árvores como forófitos, representando uma interação interespecífica neutra, onde não há prejuízos à planta hospedeira. Nessa interação, o espaço nos galhos do forófito é um importante recurso, gerando competição entre epífitas, com cenários de dominância ou coexistência, a depender do ambiente. O objetivo deste trabalho foi compreender se há relação dos microclimas com a cobertura e a coexistência de pteridófitas epífitas no forófito Tipuana tipu (Benth.) Kuntze. Nossa hipótese é que a dominância da epífita Microgramma sp. em relação a outras pteridófitas é menor em cenários de microclima mais favorável. Além disso, supomos que quanto maior o índice de vegetação maior será a cobertura vegetal total de epífitas nos galhos de Tipuana tipu. Amostramos 40 indivíduos do forófito sob diferentes condições microclimáticas. Fotografamos quadrantes de 50x50 cm, a diferentes alturas na face sul de cada Tipuana tipu (Benth.) Kuntze. Estimamos as áreas de cobertura de três morfotipos de pteridófitas mais comuns. Calculamos a dominância de Microgramma sp. sobre outras epífitas como uma proporção da área total coberta por epífitas em cada galho amostrado. Calculamos o índice normalizado de vegetação (NDVI) utilizando ortofotos de 1m de resolução e medimos o NDVI médio dentro de  buffers de 25, 50 e 100m de raio a partir do forófito. Testamos nossas hipóteses utilizando a função betareg do software R (V 4.4.2). Nosso resultado demonstra que quanto maior a média do NDVI nos buffers de 25 e 50m menor será a dominância da Microgramma sp. (p=0,010 e p=0,026, respectivamente), corroborando nossa hipótese, enquanto não houve diferença estatística no buffer de 100m (p=0,153). Adicionalmente, não houve relação estatística entre o NDVI e a cobertura das epífitas (p>0,05). Isso pode indicar que o microclima pode não ser o fator principal influenciando essa ocupação, refutando nossa segunda hipótese. Por outro lado, pudemos confirmar que o microclima é preponderante na dominância de Microgramma sp. sobre as outras samambaias epífitas, uma vez que em raios menores o efeito é significativo e em raios de 100m o efeito desaparece. Estudos anteriores afirmam que a interação entre epífitas com diferentes formas de dispersão pode ser negativa1, Microgramma sp. é a única epífita trepadeira amostrada, podendo ser dominante, mas em microclimas mais favoráveis a competição pode ser mais intensa. Como hipótese a posteriori, corroboramos que quanto maior a altura da amostra no forófito maior será a cobertura de epífitas (p=0,001), como já observado anteriormente². Os resultados obtidos auxiliam a compreender como o microclima pode influenciar na dominância entre as pteridófitas epífitas, e entender fatores que alteraram o epifitismo e competição.


**Palavras-chave:** Coexistência; microclima; Microgramma sp; pteridófitas epífitas