# Efeito da paisagem na comunidade de Euglossini em diferentes fragmentos 

> Allesson Neves; Everton Juvino; Fabiane Willes; Ingrid Neumann; Tainá Ferreira

> Orientador: Eduardo Moreira

A composição da paisagem influencia diretamente a diversidade biológica. Em paisagens complexas, espera-se maior diversidade de nichos, o que favorece a coexistência de diferentes espécies. Cenários mais heterogêneos também oferecem mais opções de abrigo e refúgio. A diversidade da tribo Euglossini, fundamental para a polinização, é afetada por variáveis estruturais da paisagem, que influenciam tanto a disponibilidade de recursos quanto a dinâmica populacional das espécies. Esse grupo, com distribuição vertical heterogênea, é considerado um bom indicador da diversidade e complexidade da paisagem devido aos seus diversos modos de vida. Este estudo investigou a relação entre a heterogeneidade ambiental, a proporção de vegetação e a abundância e riqueza de Euglossini, com a hipótese de que paisagens mais heterogêneas e vegetadas favorecem maior diversidade. As coletas foram realizadas com armadilhas de cheiro contendo eucaliptol, distribuídas em 14 pontos ao longo de um gradiente de composições de paisagem na Universidade de São Paulo - Campus Butantã e arredores, entre 07 e 10 de fevereiro de 2025. As abelhas foram triadas e identificadas até o nível de espécie. A análise da paisagem foi realizada por meio de imagens de satélite (Sentinel 1, Sentinel 2 e Alos Palsar), classificadas utilizando o algoritmo Random Forest. Para a análise, foram utilizados o índice de Shannon-Wiener e a proporção de vegetação. Modelos de regressão linear foram desenvolvidos, com riqueza e abundância de Euglossini como variáveis resposta, e o índice de Shannon e a proporção de vegetação como variáveis explicativas. Foram capturados 198 indivíduos, distribuídos nos gêneros Eulaema (125 indivíduos), Euglossa (71) e Exaerete (2), totalizando 10 espécies, sendo as mais representativas Eulaema nigrita (63,13%), Euglossa carolina (17,17%) e Euglossa solangeae (15,15%). Embora os modelos de regressão não tenham mostrado valores de p significativos, observou-se uma tendência de aumento na riqueza e abundância de Euglossini em locais com maior proporção de vegetação. Este estudo destaca a
importância de avaliar o impacto das alterações na paisagem sobre a riqueza de espécies. Estudos com mais eventos amostrais e por períodos mais longos são necessários para fortalecer os resultados.

**Palavras-chave**: Heterogeneidade; Diversidade de polinizadores; Composição; Estrutura da paisagem; Métricas espaciais;

