# O efeito da disponibilidade de recursos na distribuição de galhas foliares 

> Ana Clara Reis Duarte Magalhães¹, Bianca de Araújo Ortiz2, Carmen Morais de Gusmão da Bôaviagem³, Gabriel Henrique Bettiol4 e Jesus Eduardo Guerra Sarmiento5 

> Orientador: Miguel Piovesana Pereira-Romeiro


A disponibilidade de recursos pode influenciar a distribuição espacial dos seres vivos em diferentes escalas. Folhas podem ser encaradas como microhabitats heterogêneos, apresentando variação na disponibilidade de recursos alimentares. Insetos galhadores dependem dos recursos da folha (seiva) e, portanto, devem selecionar seu local de fixação a partir deste sinal. Temos como objetivo compreender o papel da disponibilidade de recursos na distribuição de galhas foliares. Esperamos que haja preferência pela base da nervura central (BNC) por ser uma região de maior concentração de seiva (tanto bruta quanto elaborada) quando comparado com outras regiões inervadas. Coletamos 30 folhas galhadas de 12 indivíduos (N=360) de Lauraceae na Rua do Matão (USP-Butantã). Subamostramos 77 folhas e quantificamos (I) a área de nervuras, (II) área da BNC e a presença de galhas (III) nas nervuras e (IV) da BNC. Para verificar a preferência de insetos galhadores pela BNC, realizamos um teste de Qui-Quadrado de aderência para comparar a frequência observada de folhas com galhas na BNC contra a frequência esperada. Para obter o número esperado de folhas com galhas na BNC e também nas demais nervuras, multiplicamos as médias das proporções da área da BNC e da área das demais nervuras pelo número de amostras, respectivamente. Observamos 5 folhas com galhas na BNC (esperado = 6,09) e 77 com galhas nas demais nervuras (esperado = 70,9). Não houve preferência das galhas pela BNC em relação às demais nervuras da folha (X²=0,37; p=0,054). Ainda que a BNC possua maior quantidade de recursos, sua área disponível é significativamente menor e, portanto, podemos esperar que ela rapidamente atinja uma capacidade de suporte. É possível que as ninfas prefiram selecionar outras nervuras da folha para evitar a competição por espaço e recurso na BNC às custas de recursos reduzidos.  Alternativamente, é possível que a oviposição aconteça quando as folhas ainda são jovens. Neste estágio, as nervuras do ápice foliar estão mais maduras que as da BNC (desenvolvimento basípeto). Dessa forma, pode haver uma preferência das ninfas por áreas mais desenvolvidas, independente do padrão de nervação observado numa folha adulta. Estes processos podem ser alguns dos que explicam o padrão observado. Não podemos afirmar que haja algum mecanismo de escolha de posição da galha em relação aos recursos disponíveis na folha. Ressaltamos a necessidade de mais estudos deste tipo, considerando que os mecanismos de indução de galha ainda são pouco estudados, especialmente nos neotrópicos. 


**Palavras-chave**: Psylloidae; nervação foliar; parasitismo; interação inseto-planta; Lauraceae
