# A influência da escolha do recurso alimentar sobre o fitness em besouros brocadores

> Beatriz M. Maenaka, Gabriel R. Silva, Helena Gallindo, Isabel Alves, e Lucas Melquiades, Lucas Freitas

> Orientador: Lucas Freitas e Gabriel Nakamuram

Os organismos são selecionados para otimizar a obtenção de energia e minimizar os custos associados à manipulação de recursos, aumentando as chances de sobrevivência e sucesso reprodutivo. Os besouros brocadores (e.g., Bruchidae) possuem um ciclo de vida parasitoide, colocando ovos na superfície externa de frutos, que fornecem abrigo e nutrientes para o desenvolvimento das larvas. Ao eclodirem, as larvas deixam cavidades circulares na superfície do fruto. Este estudo testou como a escolha de recursos alimentares afeta a aptidão da prole. Segundo a teoria de forrageamento ótimo, esperamos que larvas com maior aptidão estejam associadas a frutos com mais recursos, enquanto larvas com menor aptidão seriam associadas a frutos com maior custo energético de manipulação. Para testar essa hipótese, coletamos frutos caídos ao redor das palmeiras do Jardim Japonês da USP. Medimos o volume dos frutos com paquímetro (precisão de 0,01 mm), utilizando a fórmula do cilindro, e a espessura da casca para quantificar o custo de manipulação. Como medida de aptidão, analisamos o diâmetro da cavidade de saída das larvas. Trabalhamos com 100 frutos, e para evitar efeitos de confusão devido ao uso compartilhado do recurso por diferentes espécies, visualizamos a distribuição do diâmetro das cavidades com um histograma. Ao identificar uma distribuição bimodal, excluímos frutos com cavidades menores que 2,5 mm (n = 16), assumindo que pertenciam a outra espécie de besouro. Os frutos com cavidades maiores ou iguais a 2,5 mm (n = 84) foram analisados. Testamos os efeitos do volume do fruto e da espessura da casca sobre o diâmetro da cavidade de saída das larvas com regressões lineares. O volume do fruto influenciou positivamente a aptidão (R² = 10,03%, p = 0,01, coeficiente angular = 0.12), mas a espessura da casca não teve efeito significativo (R² = -0,001%, p = 0,35, coeficiente angular = -0.05), indicando que o custo de manipulação da casca não limita a aptidão. Não encontramos interação significativa entre volume e espessura da casca (R² = 11,57%, p = 0,02), destacando a importância da quantidade de recursos na aptidão das larvas. Nossos resultados indicam que o sucesso reprodutivo dos besouros brocadores está relacionado com a disponibilidade de recursos nos frutos, e a baixa importância da espessura da casca sugere que fatores ambientais, como a quantidade de frutos ou a presença de ovos de outros indivíduos, também influenciam a escolha do local de desova.



**Palavras-chave**: Besouro brocador; trade-off; esforço de manipulação; fitness; forrageamento ótimo.

