# Vizinhar ou não vizinhar, eis a questão 

> Grupo 5: Augusto Carvalho, Catarina Albuquerque, Larissa Vidal e Vitor Zanelatto

> Orientadora: Amanda Vieira da Silva 


A formação de agregações coespecíficas é um hábito amplamente distribuído em diferentes animais, sendo facultativa ou obrigatória dependendo do grupo. Em espécies que se agregam de modo facultativo, a limitação ao acesso aos recursos pode ser um fator importante na decisão de estar solitário ou agregado. Recursos alimentares, por exemplo, talvez sejam mais facilmente obtidos em agregações, entretanto, a competição intraespecífica por acesso a esses recursos também pode reduzir a chance individual de obtenção de alimento. Além dos recursos alimentares, a chance de encontrar um parceiro sexual pode ser maior em agregações do que para indivíduos que vagueiam solitariamente. Uma espécie que pode ser encontrada tanto de forma solitária quanto em agregações é a aranha de teia dourada Triconephila clavipes (Linnaeus, 1767), sugerindo a existência de demandas conflitantes entre esses dois hábitos. Neste estudo, investigamos se fêmeas em teias agregadas e isoladas apresentam condição nutricional diferentes entre si e também se fêmeas de teias agregadas apresentam maior aptidão sexual que de teias isoladas. Para isso, contabilizamos e categorizamos teias solitárias e agregadas de T. clavipes em um fragmento de Mata Atlântica. Como estimativa da condição nutricional, medimos a área dorsal do abdômen de fêmeas adultas. Para aptidão sexual, calculamos a proporção de fêmeas sem machos nas teias focais. Nós vimos que o número médio de fêmeas por agregação foi cinco. Não encontramos correlação entre a área abdominal das fêmeas e a agregação ou isolamento das teias. Além disso, a frequência de fêmeas sem machos não diferiu entre os hábitos e, em ambos os casos, a presença de machos foi superior a 70%. Contrário ao esperado, o hábito de agregação não afeta a condição nutricional e a aptidão sexual das fêmeas. Entretanto, outros mecanismos poderiam explicar os hábitos de agregação das fêmeas. Por exemplo, a limitação de habitats disponíveis resultaria em um processo estocástico de agregação espacial, acarretando na competição entre os indivíduos que compõem uma agregação, de modo que a aptidão individual não seja uniforme dentro dos grupos. Além disso, indivíduos em agregações possuem vantagens na fuga de predadores, a pressão de predação favoreceria a permanência desse hábito na espécie. Os mecanismos exatos que estruturam a distribuição dessa espécie ainda não são claros, evidenciando a relevância de futuras pesquisas acerca da distribuição dos indivíduos, contribuindo na compreensão do comportamento animal e dos processos evolutivos que o moldam. 


**Palavras-chave:** agregação, aptidão sexual; recursos alimentares; distribuição espacial; *Trichonephila clavipes*. 